#Database config
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/octoger
    username: nmatute
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#springboot config
server:
    port: 9010
    secretEncryptionKey: myKey

logging:
  level:
    root: DEBUG
